# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 14.x ]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            -   run: npm ci
            -   run: npx semantic-release
            -   name: Build Web App
                run: |
                    echo "Build Web App"
            -   uses: convictional/trigger-workflow-and-wait@v1.3.0
                with:
                    owner: keithweaver
                    repo: demo-web-api
                    github_token: ${{ secrets.G_ACCESS_TOKEN }}
                    workflow_file_name: deploy.yml
            -   name: Deploy Web App
                run: |
                    echo "Deploy Web App"s
